In [75]:
import sys
sys.path.append('/usr/local/lib/python3.9/site-packages/')
import bisect
import math
import matplotlib as plt
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import numpy as np
import copy

In [76]:
#Pandas is kinda like numpy except better for heterogenous data
#Series is equiv of numpy array
pds=Series([1,2,5,6])
print (pds)

0    1
1    2
2    5
3    6
dtype: int64


In [77]:
#pandas indices 
print(pds.index)
print(list(pds.index))

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]


In [78]:
#kinda like an ordered dict
pds1=Series([1,2,5,6],index=["a","b","c","d"])
print (pds1)
print (pds1.index)

a    1
b    2
c    5
d    6
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')


In [79]:
#can do numpy like index broadcasting
print (pds1[pds1>3])
print (pds1*3)
print ("x" in pds1)

c    5
d    6
dtype: int64
a     3
b     6
c    15
d    18
dtype: int64
False


In [80]:
#dict to pd -- Order is from Sorted
pyd={"Ohio":70000,"Texas":3000,"Utah":400000,"Vermont":10}
pds2=Series(pyd)
print (pds2)
pds2=Series(pyd,["Ohio","Texas","Virginia"])
print (pds2)

Ohio        70000
Texas        3000
Utah       400000
Vermont        10
dtype: int64
Ohio        70000.0
Texas        3000.0
Virginia        NaN
dtype: float64


In [81]:
#find missing data
print (pd.isnull(pds2))
print (pd.notnull(pds2))
print (pds2[pd.notnull(pds2)])
print (pds2[pds2.notnull()])
print (pds2[pds2.isnull()])

Ohio        False
Texas       False
Virginia     True
dtype: bool
Ohio         True
Texas        True
Virginia    False
dtype: bool
Ohio     70000.0
Texas     3000.0
dtype: float64
Ohio     70000.0
Texas     3000.0
dtype: float64
Virginia   NaN
dtype: float64


In [82]:
#mathematical operations align be index 
#Always use pandas for database stuff!
pyd1={"Ohio":2,"Texas":15,"Utah":3,"Vermont":20,"Wyoming":6}
pds3=Series(pyd)
print(pds3+pds2)

Ohio        140000.0
Texas         6000.0
Utah             NaN
Vermont          NaN
Virginia         NaN
dtype: float64


In [83]:
#Can give names to indices -- like dict of dict?
#Probably most pandas objects have a name attribute

pds2.name="population"
pds2.index.name="state"
print (pds2)

#can alter index names in order
pds2.index=['Ohio', 'Texas', 'Iowa']
print (pds2)

state
Ohio        70000.0
Texas        3000.0
Virginia        NaN
Name: population, dtype: float64
Ohio     70000.0
Texas     3000.0
Iowa         NaN
Name: population, dtype: float64


In [91]:
#Dataframes!  Pandas dict of series
# to create a DataFrame, use dict of list (or np array)
dictdata =  {
            "state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
            "year":[2000,2001,2002,2000,2001,2002],
            "pop":[1.1,1.4,1.9,1.3,1.5,1.7]
            }
df=DataFrame(dictdata)
print (df)

    state  year  pop
0    Ohio  2000  1.1
1    Ohio  2001  1.4
2    Ohio  2002  1.9
3  Nevada  2000  1.3
4  Nevada  2001  1.5
5  Nevada  2002  1.7


In [92]:
#can organize dataframe columns
print (df.columns)
df.columns=[ 'year', 'state', 'pop']
print (df)
#column row is column index
df=DataFrame(dictdata,columns=[ 'year', 'state', 'pop', 'debt'],index=["one","two","three","four","five","six"])
print (df)


Index(['state', 'year', 'pop'], dtype='object')
     year  state  pop
0    Ohio   2000  1.1
1    Ohio   2001  1.4
2    Ohio   2002  1.9
3  Nevada   2000  1.3
4  Nevada   2001  1.5
5  Nevada   2002  1.7
       year   state  pop debt
one    2000    Ohio  1.1  NaN
two    2001    Ohio  1.4  NaN
three  2002    Ohio  1.9  NaN
four   2000  Nevada  1.3  NaN
five   2001  Nevada  1.5  NaN
six    2002  Nevada  1.7  NaN


In [93]:
#column names are both dict indices and functional properties
#returns a pandas Series
print (df["year"])
print (df.state)

one      2000
two      2001
three    2002
four     2000
five     2001
six      2002
Name: year, dtype: int64
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object


In [94]:
df=copy.deepcopy(df)

print (df["debt"])
df["debt"]=16.
print (df["debt"])
df["debt"]=[1.1,1.2,1.3,1.4,1.5,1.6]
print (df["debt"])

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object
one      16.0
two      16.0
three    16.0
four     16.0
five     16.0
six      16.0
Name: debt, dtype: float64
one      1.1
two      1.2
three    1.3
four     1.4
five     1.5
six      1.6
Name: debt, dtype: float64


In [97]:
#Adding data to Dataframe
#use a series
pdmerge=pd.Series([1.1,2.4,2.5],index=["one","three","five"])
df["debt"]=pdmerge
print(df)
print (df.isnull())

       year   state  pop  debt
one    2000    Ohio  1.1   1.1
two    2001    Ohio  1.4   NaN
three  2002    Ohio  1.9   2.4
four   2000  Nevada  1.3   NaN
five   2001  Nevada  1.5   2.5
six    2002  Nevada  1.7   NaN
        year  state    pop   debt
one    False  False  False  False
two    False  False  False   True
three  False  False  False  False
four   False  False  False   True
five   False  False  False  False
six    False  False  False   True


In [101]:
#Frame uses math arguments on the seres specifies
Est=(df.state=="Ohio")
df["eastern"]=Est
print(df)
del df["eastern"]
print(df)



       year   state  pop  debt  eastern
one    2000    Ohio  1.1   1.1     True
two    2001    Ohio  1.4   NaN     True
three  2002    Ohio  1.9   2.4     True
four   2000  Nevada  1.3   NaN    False
five   2001  Nevada  1.5   2.5    False
six    2002  Nevada  1.7   NaN    False
       year   state  pop  debt
one    2000    Ohio  1.1   1.1
two    2001    Ohio  1.4   NaN
three  2002    Ohio  1.9   2.4
four   2000  Nevada  1.3   NaN
five   2001  Nevada  1.5   2.5
six    2002  Nevada  1.7   NaN


In [110]:
#You can interpret a dict of dicts as a dataframe
#Outer dict is collumn, inner is row

pop={
        "Nevada":{2001:2.4,2002:2.9},
        "Ohio":{2000:1.1,2001:1.4,2002:2.2}
    }
df=pd.DataFrame(pop)
print (df)

#transpose
print(df.T)

      Nevada  Ohio
2001     2.4   1.4
2002     2.9   2.2
2000     NaN   1.1
        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.4   2.2   1.1


In [119]:
print (df.index)
df=pd.DataFrame(pop,index=[2001, 200, 2000,2003])
print (df)

#reindexing
print (df.reindex([2001, 2002, 2000,2003,2004]))

Int64Index([2001, 2002, 2000, 2003], dtype='int64')
      Nevada  Ohio
2001     2.4   1.4
200      NaN   NaN
2000     NaN   1.1
2003     NaN   NaN
      Nevada  Ohio
2001     2.4   1.4
2002     NaN   NaN
2000     NaN   1.1
2003     NaN   NaN
2004     NaN   NaN


In [143]:
#you can use ffill to do excel like extrapolations
colseries=pd.Series(["blue","purplle","yelllow"],index=[0,4,5])
colseries=colseries.reindex(np.arange(6),method="ffill")
print (colseries)
#OR
#colseries=colseries.ffill()
#print (colseries)


0       blue
1       blue
2       blue
3       blue
4    purplle
5    yelllow
dtype: object


In [147]:
newdf=pd.DataFrame(np.arange(9).reshape(3,3),index=["a","b","d"],columns=["Ohio","Texas","Virginia"])
#reindex assumes row in a DataFrame
newdf=newdf.reindex(["a","b","c","d"])
#to reindex columns
print (newdf.columns)
newdf=newdf.reindex(columns=["Ohio","Virginia","Texas","Zoop"])

print (newdf)

Index(['Ohio', 'Texas', 'Virginia'], dtype='object')
   Ohio  Virginia  Texas  Zoop
a   0.0       2.0    1.0   NaN
b   3.0       5.0    4.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN


In [157]:
#index dropping 
newdf=copy.deepcopy(newdf)
newdf1=newdf.drop("b")
print(newdf1)
newdf1=newdf.drop(index=["b","d"])
print(newdf1)
newdf1=newdf.drop(columns=["Virginia"])
print(newdf1)
#can be done with axis number

newdf1=newdf.drop(columns=["Texas"],axis=1)
print(newdf1)
newdf1=newdf.drop(columns=["Zoop"],axis="columns")
print(newdf1)


   Ohio  Virginia  Texas  Zoop
a   0.0       2.0    1.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN
   Ohio  Virginia  Texas  Zoop
a   0.0       2.0    1.0   NaN
c   NaN       NaN    NaN   NaN
   Ohio  Texas  Zoop
a   0.0    1.0   NaN
b   3.0    4.0   NaN
c   NaN    NaN   NaN
d   6.0    7.0   NaN
   Ohio  Virginia  Zoop
a   0.0       2.0   NaN
b   3.0       5.0   NaN
c   NaN       NaN   NaN
d   6.0       8.0   NaN
   Ohio  Virginia  Texas
a   0.0       2.0    1.0
b   3.0       5.0    4.0
c   NaN       NaN    NaN
d   6.0       8.0    7.0


In [175]:
#indexing Series
pds1=Series([1,2,5,6],index=["a","b","c","d"])
print(pds1)
pds1["b":"d"]=5
print(pds1)

print(pds1["a":"c"]==5)
newdf1=newdf
newdf2=newdf1["b":"d"]
print (newdf2)
#conditions turn into Nan
newdf2=newdf1[newdf1>4]
print (newdf2)
newdf2=newdf1.copy()
print (newdf2)
newdf2[newdf2<5]=0
print (newdf2)


a    1
b    2
c    5
d    6
dtype: int64
a    1
b    5
c    5
d    5
dtype: int64
a    False
b     True
c     True
dtype: bool
   Ohio  Virginia  Texas  Zoop
b   3.0       5.0    4.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN
   Ohio  Virginia  Texas  Zoop
a   NaN       NaN    NaN   NaN
b   NaN       5.0    NaN   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN
   Ohio  Virginia  Texas  Zoop
a   0.0       2.0    1.0   NaN
b   3.0       5.0    4.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN
   Ohio  Virginia  Texas  Zoop
a   0.0       0.0    0.0   NaN
b   0.0       5.0    0.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN


In [184]:
#pandas loc and iloc select rows and columns by name
newdf2=newdf1.copy()
print (newdf2)
print(newdf2.loc[["a","d"],["Ohio","Texas"]])
print(newdf2.iloc[[1,3],[0,1]])

   Ohio  Virginia  Texas  Zoop
a   0.0       2.0    1.0   NaN
b   3.0       5.0    4.0   NaN
c   NaN       NaN    NaN   NaN
d   6.0       8.0    7.0   NaN
   Ohio  Texas
a   0.0    1.0
d   6.0    7.0
   Ohio  Virginia
b   3.0       5.0
d   6.0       8.0


In [191]:
ser = pd.Series(np.arange(3.))
print(ser)
print(ser[1])#-1 does not work b/c integer indices
ser.index=["a","b","c"]
print(ser)
print(ser[-1])


0    0.0
1    1.0
2    2.0
dtype: float64
1.0
a    0.0
b    1.0
c    2.0
dtype: float64
2.0


In [193]:
#Series inex joining
ser1 = pd.Series(np.arange(3.),index=["a","b","c"])
ser2 = pd.Series(np.arange(4.),index=["a","b","c","d"])
print(ser1)
print(ser2)
print(ser2+ser1)
#ONLY data values in overlaps, everything else in Nan

a    0.0
b    1.0
c    2.0
dtype: float64
a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
a    0.0
b    2.0
c    4.0
d    NaN
dtype: float64


In [197]:
#You can control overlaps with fillvalue
ser1 = pd.Series(np.arange(3.),index=["a","b","c"])
ser2 = pd.Series(np.arange(4.),index=["a","b","c","d"])
print(ser2.add(ser1,fill_value=0.))

a    0.0
b    2.0
c    4.0
d    3.0
dtype: float64


In [223]:
#Broacasting means performing an operation axiswise
curarr=np.arange(12).reshape(4,3)
print(curarr)
print(curarr-curarr[0])

#can also be done to pandas objects
curdf=pd.DataFrame(np.arange(12).reshape(4,3),columns=list('bde'),index=["Ohio","Virginia","Texas","Zoop"])
print (curdf)
curser=curdf.loc["Virginia"]
print(curser)

#Note, by index!
print (curdf.sub(curser,axis=1))

curser=curdf.loc[:,"b"]
print(curser)

print (curdf.sub(curser,axis=0))
print (curdf.sub(2*curser,axis=0))
#pandas works with numpy ufuncs
print (np.abs(curdf.sub(2*curser,axis=0)))




[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0 0]
 [3 3 3]
 [6 6 6]
 [9 9 9]]
          b   d   e
Ohio      0   1   2
Virginia  3   4   5
Texas     6   7   8
Zoop      9  10  11
b    3
d    4
e    5
Name: Virginia, dtype: int64
          b  d  e
Ohio     -3 -3 -3
Virginia  0  0  0
Texas     3  3  3
Zoop      6  6  6
Ohio        0
Virginia    3
Texas       6
Zoop        9
Name: b, dtype: int64
          b  d  e
Ohio      0  1  2
Virginia  0  1  2
Texas     0  1  2
Zoop      0  1  2
          b  d  e
Ohio      0  1  2
Virginia -3 -2 -1
Texas    -6 -5 -4
Zoop     -9 -8 -7
          b  d  e
Ohio      0  1  2
Virginia  3  2  1
Texas     6  5  4
Zoop      9  8  7


In [234]:
# you can make rowwise of columnwise functions in pandas from python functions
func=lambda x : x.max() - x.min()
curdf1=curdf.copy()
print(curdf1)
print (curdf1.apply(func,axis=0))
print (curdf1.apply(func,axis=1))

# func can also return a series
def func1(x):
    return pd.Series([x.min(),x.max()],index=["min","max"])
print (curdf1.apply(func1,axis=1))


          b   d   e
Ohio      0   1   2
Virginia  3   4   5
Texas     6   7   8
Zoop      9  10  11
b    9
d    9
e    9
dtype: int64
Ohio        2
Virginia    2
Texas       2
Zoop        2
dtype: int64
          min  max
Ohio        0    2
Virginia    3    5
Texas       6    8
Zoop        9   11


In [253]:
#sorting
curdf1=curdf.copy()
curdf1=curdf1.reindex(["e","d","b"],axis=1)
print (curdf1.index)
curdf1=curdf1.reindex(['Zoop','Ohio', 'Virginia', 'Texas', ],axis=0)

print(curdf1)
print(curdf1.sort_index(axis=1))
print(curdf1.sort_index(axis=0))
print(curdf1.sort_values(axis=1,by="Texas"))
print(curdf1.sort_values(axis=0,by="b"))
#giving sort a list for the "by" method sorts first elem then second if tie 




Index(['Ohio', 'Virginia', 'Texas', 'Zoop'], dtype='object')
           e   d  b
Zoop      11  10  9
Ohio       2   1  0
Virginia   5   4  3
Texas      8   7  6
          b   d   e
Zoop      9  10  11
Ohio      0   1   2
Virginia  3   4   5
Texas     6   7   8
           e   d  b
Ohio       2   1  0
Texas      8   7  6
Virginia   5   4  3
Zoop      11  10  9
          b   d   e
Zoop      9  10  11
Ohio      0   1   2
Virginia  3   4   5
Texas     6   7   8
           e   d  b
Ohio       2   1  0
Virginia   5   4  3
Texas      8   7  6
Zoop      11  10  9


In [265]:
#duplicate labels 
pds=pd.Series(np.arange(5),index=["a","a","b","b","c"])
print(pds)
print(pds.index.is_unique)
print(pds["b"])
#same for dataframes

#you can do lots of np type operations
curdf1=curdf.copy()
print(print(curdf1))
print(curdf1.cumsum(axis=1))


a    0
a    1
b    2
b    3
c    4
dtype: int64
False
b    2
b    3
dtype: int64
          b   d   e
Ohio      0   1   2
Virginia  3   4   5
Texas     6   7   8
Zoop      9  10  11
None
          b   d   e
Ohio      0   1   3
Virginia  3   7  12
Texas     6  13  21
Zoop      9  19  30


In [276]:
#setlikes
pds=pd.Series(["a","a","a","a","a","a","a","a","b","c","c","c"])
print (pds.unique())
print (pds.value_counts())
print (pds)

print (pds.isin(["b","c"]))

['a' 'b' 'c']
a    8
c    3
b    1
dtype: int64
0     a
1     a
2     a
3     a
4     a
5     a
6     a
7     a
8     b
9     c
10    c
11    c
dtype: object
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
dtype: bool
