In [2]:
import sys
sys.path.append('/usr/local/lib/python3.9/site-packages/')


import seaborn as sns
import bisect
import math
import matplotlib as plt
import pandas as pd
from pandas import Series,DataFrame
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import copy
import json
import lxml
from lxml import objectify 
from datetime import datetime
import scipy
from dateutil.parser import parse

In [3]:
#categorial tipe in pandas (good for ML!)
fruits=["apple","apple","apple","orange"]*2
Nf= len(fruits)
fruitframe=pd.DataFrame({"basketid":np.arange(Nf),"fruit":fruits,"count":np.random.randint(0,10,Nf),"weight":np.random.uniform(0,10,Nf)})
fruitcat=fruitframe["fruit"].astype("category")
print(fruitcat)
print(fruitcat.values.codes)

0     apple
1     apple
2     apple
3    orange
4     apple
5     apple
6     apple
7    orange
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']
[0 0 0 1 0 0 0 1]


In [4]:
#you can go the other way too
catsstr=["zoop","bloop","taco"]
cats=pd.Categorical.from_codes([0,0,1,1,2,1,0],catsstr)
print (cats.codes)
#One hot encoding 
pd.get_dummies(cats)

[0 0 1 1 2 1 0]


zoop  bloop  taco
0     1      0     0
1     1      0     0
2     0      1     0
3     0      1     0
4     0      0     1
5     0      1     0
6     1      0     0

In [16]:
#Advanced Numpy
#Broadcasting -- taking a low dim object through a high dim object
nparr=np.arange(5)
nparr*5
#Broadcasting works if all of the dimensions match and one is 1. 
#then broadcat over "1" dimension

#row

nparr1=np.arange(30).reshape(3,-1)
print (nparr1.shape)
brarr=np.arange(10)-1
print (brarr.shape)
print (nparr1)

print (brarr)

print (nparr1-brarr)
print (nparr1*brarr)

(3, 10)
(10,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[-1  0  1  2  3  4  5  6  7  8]
[[ 1  1  1  1  1  1  1  1  1  1]
 [11 11 11 11 11 11 11 11 11 11]
 [21 21 21 21 21 21 21 21 21 21]]
[[  0   0   2   6  12  20  30  42  56  72]
 [-10   0  12  26  42  60  80 102 126 152]
 [-20   0  22  46  72 100 130 162 196 232]]


In [22]:
#column

nparr1=np.arange(30).reshape(3,-1)
print (nparr1.shape)
brarr=(np.arange(3)-1).reshape(3,1)

print (brarr.shape)
print (nparr1)
print (brarr)

print (nparr1-brarr)
print (nparr1*brarr)

#numoy also has structured array which alllow multi-dtype.  kinda similat to a dataframe


(3, 10)
(3, 1)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[-1]
 [ 0]
 [ 1]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [10 11 12 13 14 15 16 17 18 19]
 [19 20 21 22 23 24 25 26 27 28]]
[[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
 [ 0  0  0  0  0  0  0  0  0  0]
 [20 21 22 23 24 25 26 27 28 29]]
